project:
  type: website
  output-dir: docs
resources:
  - figures/
  
website:
  title: "Tweety's website"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: hw1_questions.qmd
        text: A/B Testing
      - href: hw2_questions.qmd
        text: MLE
      - href: hw3_questions.qmd
        text: MNL & Conjoint
      - href: hw4_questions.qmd
        text: Key Drivers Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true