project:
  type: website
  output-dir: docs
  resources:
    - figures/

execute:
  python: .venv/bin/python
  echo: false
  warning: false
  message: false

website:
  title: "Tweety's website"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: credit_card_fraud_detection.qmd
        text: Fraud Detection
      - href: Intuit_Quickbooks_Upgrade.qmd
        text: Uplift Modeling
      - href: database_management.qmd
        text: Database Management
      - href: AB_Testing.qmd
        text: A/B Testing
      - href: Maximum_Likelihood_Estimation.qmd
        text: MLE
      - href: Key_Drivers_Analysis.qmd
        text: K-Means Clustering

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true