project:
  type: website
  output-dir: docs
  resources:
    - figures/

execute:
  python: .venv/bin/python

website:
  title: "Tweety's website"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: AB_Testing.qmd
        text: A/B Testing
      - href: Maximum_Likelihood_Estimation.qmd
        text: MLE
      - href: Multinomial_Logit_Model.qmd
        text: MNL & Conjoint
      - href: Key_Drivers_Analysis.qmd
        text: Key Drivers Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true